language: generic
env:
  global:
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="production-line"
    - REPO_DEST="production-line.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: uKh+EP76A88JLQ+nb1c/pLcxNjCiXh9VrOs0kD9kg0zADHSBitv31GbBjo2Vk/fWOq+zywsqw0u1d8ouDu8SUxajQQqFEnJ5ofpLzjPeAA6ddUDB9dTDmIc40eJM9rrXmqd29X/HwlT3Zdf0AswPS74NYnWK5rlLiUSlUs+K1yFYRv49ZeX5dX6XlMR6RFReoMRE124QZAK+7TD7KEe4vN0DBr6eyJtCYYlg/QlddZJfljCfeHHaKUBBkS7ftBmZAbWSqfKHDtLiSGKLnIRQRvtjDxqgYHTDp1AvAlNUVkeWvh0hRuynRe+vhwpgUJNLlJ0EUllKuPffUZpPqissi7H5RxzrXKF7g3yLWVdczS15Fn6ZqtW6Q6ekrVUGmxAYVeiJUe3I+Kql2aivDIQWatbwFPtvm/3PySbwkx719BBiIpeScsk6e8CJxOe8+W/ITr4rIFCHR5VjaA+lG+1nSdf9pebmQOpd/z4vwYUhcQl4ho0b82NFIoiDyuch/BI34nilUZs4/ltf873C4AvBdXiyxg1nHlt/FvN8/95c2zZcGk9DRu+kNVYKwUEntK0fg/qgPoWbWg60Y0ihjJvmsGKGLg5KKoZZsUnaZ5qSoe04BWV0xtWhAdM9RikmrZZB7/L5cQfhfmlCndbUt4kKeV+G6ufu0Achzd11voLEdFg=
stages:
  - name: Documentation
    if: (branch = master) AND (type = push)
jobs:
  include:
    - stage: Documentation
      script:
        # Clone repositories
        - git clone -b master --single-branch https://${GH_REPO_SOURCE}
        - git clone https://${GH_REPO_DEST}
        - git clone https://${GH_REPO_CONSOLIDATE}
        # Update wiki repository with documentation folder contents
        - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
        - cd ${REPO_DEST}
        - grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
        # Terminate Travis CI build when no changes detected
        - |
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            git config user.email ${EMAIL}
            git config user.name ${USER}
            git status
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
            git push origin-wiki master
            cd ../${REPO_CONSOLIDATE}
            if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
            git submodule init
            git submodule update --recursive --remote
            cd ${REPO_DEST}
            git checkout master
            git pull
            cd ..
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
            git push origin-wiki master
          fi
